doc/tutorial.rst, xija/component/base.py, xija/model.py
This allows adding the following to a JSON model file to define time intervals that are ignored in fitting:
```
{
"bad_times": [
[
"2014:001", 
"2014:003"
], 
[
"2014:010", 
"2014:013"
]
], 
"comps": [
{
"class_name": "Mask",  
....
```
Technically, the fit residuals are not ignored but are zeroed out.
=> Add bad_times model attributes to mask out resids during bad times

xija/model.py
Previously bad time intervals that are outside of the model time range would result in a null interval, with indices `[0, 0]`.  This was fine for fitting but crashed the plotting.
=> Don't include bad time intervals that are null

xija/component/heat.py, xija/gui_fit.py
This should make the typical model fitting process easier by recentering the model `epoch` for `SolarHeat`-based models that have linear long-term dependence.  This behavior is the default, but it can be disabled by passing the `--keep-epoch` flag when calling `gui_fit.py`.
A typical fitting sequence could then be:
1. Fit the solar heat `P` parameters for the most recent year of data, letting `gui_fit` recenter the epoch.  In this stage leave the `dP` values at the previous best fit values (do not zero the out).  Save and close.
2. Ft the solar heat `dP` parameters for the most recent 2-3 years, using the `--keep-epoch` flag to maintain the epoch at the center of the 1-year fit.  In this way the epoch refers to the center of the data used to determine the solar heat `P` values. …
=> Make gui_fit recenter epoch on fit window by default for linear models

xija/component/base.py, xija/component/heat.py, xija/version.py
Add heating of a +Y or -Y face of a spacecraft component due to off-nominal roll.  The
heating is proportional to the projection of the sun on body +Y axis (which is a value
from -1 to 1).  There are two parameters `P_plus_y` and `P_minus_y`.  For sun on
the +Y side the `P_plus_y` parameter is used, and likewise for sun on -Y.  For
example for +Y sun:
heat = P_plus_y * sun_body_y
The following reference has useful diagrams concerning off-nominal roll and
projections: http://occweb.cfa.harvard.edu/twiki/pub/Aspect/WebHome/ROLLDEV3.pdf.
=> Add SolarHeatOffNomRoll and Roll components

xija/__init__.py, xija/component/heat.py
The ACIS Ops team has discovered that the single `hrc_bias` parameter which adjusts the expected pitch-dependent solar heating if HRC is in the focal plane is not sufficient to reproduce the temperature behavior for both cases: HRC-I is in the focal plane or HRC-S. Since we spend far more time with HRC-S in the focal plane, this parameter is calibrated well for that case but not for HRC-I.
~~This PR allows a thermal model specification to specify that two bias parameters should be set by setting the `hrc_bias` parameter in  the `SolarHeatHrc` class constructor to a 2-element iterable such as a list, which can be done in the JSON file. This creates two bias parameters, `hrci_bias` and `hrcs_bias`, which then will correspond to the different SIM positions.~~
~~My original thought was to …
=> Allow for two "hrc_bias" parameters

xija/__init__.py, xija/component/heat.py, xija/gui_fit.py
In the next version of `taco`, it will be a top-level package. This PR makes sure that regardless of whether `taco` is installed or `Chandra.taco` is installed, it can be used with `xija`.
=> Support the (soon-to-be) latest version of taco

xija/__init__.py, xija/component/heat.py
Based on the nice idea from @matthewdahmer this includes the 1-year extrapolation of solar heating by pitch.   E.g.
=> Improve solar heat pitch plot in gui_fit

xija/__init__.py, xija/component/base.py, xija/tests/test_models.py
This expands the upper end of the supported pitch range from 170 degrees (169.999 degrees) to 180 degrees (179.999 degrees) to reflect the expanded allowable pitch range being explored.
=> Expand the upper end of the supported pitch range from 170 to 180 degrees

.gitignore, xija/__init__.py, xija/component/heat.py
The current code for computing the yearly variation in solar heating due to the change in the Earth's distance to the Sun has a bug. The mathematical background which led me to discover this is found here:
[solarheat_orbit.pdf](https://github.com/sot/xija/files/3302107/solarheat_orbit.pdf)
This PR does the following things:
- Fixes the variation in solar heating
- ~~Adds this effect to the `SolarHeatOffNomRoll` and `EarthHeat` classes by creating a `SolarHeatBase` superclass which `SolarHeat` and its subclasses also use.~~
- Adds a new `NewSolarHeat` class so we can implement this fix in models one by one without having to change them all at once. Eventually the `NewSolarHeat` class should replace the `SolarHeat` class. 
Preliminary tests using the ACIS DPA and DEA models show …
=> Add option for multiplicative yearly dependence of solar heating

xija/model.py
Most models have a `dt` of 328 seconds as the default. The ACIS DEA Housekeeping telemetry (most importantly the focal plane temperature) has a much higher time resolution than this. 
Currently in xija even if a smaller `dt` is specified in the model specification it is not changed when the model is run. This PR makes some modest changes to allow the timestep to be ingested from the model specification. In most cases, models will set the `dt` to 328 seconds, and the code here ensures that the default does not change.
=> Allow the timestep to be set from the model specification

.github/workflows/build.yml
This is a tiny change to the github actions I just introduced in the last PR. It allows one to trigger the conda build using the REST API. It just might be useful.
=> enable triggering conda build using repository dispatch

xija/component/base.py
This is a quick hotfix for `gui_fit` (I am a bit sheepish about this). During a fit, the data line is being updated in the plot with the model instead of the model line.
This does not affect the model propagation or fitting, and at the end of the fit the model and data lines are correct, but this should fix the model misleadingly looking like a perfect fit while the fit is running. 
- [ x] Passes unit tests on MacOS, linux, Windows (at least one required)
- [ x] Functional testing
Fixes #
=> [bugfix] Wrong line is updated in gui_fit

xija/component/base.py, xija/tests/test_models.py
This fixes a 7+ year old bug when trying to do something like:
```
mdl.comp['solarheat__pf0tank2t'].P_60 = 5.0
mdl.calc()
```
Note that a work-around right now is:
```
mdl.comp['solarheat__pf0tank2t'].pars_dict['P_60'] = 5.0
```
=> Fix bug in component param set attribute

pytest.ini, setup.cfg, xija/component/experimental.py, xija/component/heat.py, xija/tests/test_models.py
This changes epoch dates like `2010:001` to a fully-qualified string like `2010:001:12:00:00` so regression tests all pass in shiny with Chandra.Time 4.0+.
It also includes the standard pytest filters to ignore useless warnings.
See also: https://github.com/sot/skare3/wiki/Shiny-Ska3
- [N/A] Functional testing
=> Fixes for tests for shiny

xija/model.py, xija/tests/test_models.py
Use kadi command states instead of Chandra.cmd_states.
This uses `kadi.commands.states.interpolate_states` which does not exist in flight. Since the change to using kadi states is slightly controversial, we'll just carry this in the `shiny` branch for now.  However, if the latest `kadi` were installed to flight then these tests should pass.
Ran gui_fit and confirmed that commanded states are read in and the model predition seems reasonable by eye.
=> SHINY: use kadi command states instead of Chandra.cmd_states

xija/component/heat.py
This allows including multiple instances of the StepFunctionPower component on the same node by adding an `id` attribute. This identifier is put into the component name (via the __str__ function). The default `id` is an empty string for back-compatibility.
**Reminder**: this needs to be ported to the `shiny` branch (by cherry-pick or rebase).
To make the model more self-documenting, I would recommend setting the `id` to be the date of the step, for instance `_2020213` for the July 31 swap.
Reviewed and approved by TWG on July 21, 2020.
Made a new ACA model `aca_spec_3_step` which has a step function up at 2020:100 and same step function back down at 2020:120. This shows that the additional step functions are having the intended effect:
- No impact on model predictions prior to 2020:100
- …
=> Enhance StepFunctionPower component to allow multiple instances

docs/conf.py, xija/__init__.py, xija/clogging.py, xija/component/base.py, xija/component/heat.py, xija/component/mask.py, xija/gui_fit/app.py, xija/gui_fit/fitter.py, xija/gui_fit/plots.py, xija/gui_fit/utils.py, xija/model.py, xija/tests/test_models.py
This migrates all the docstrings for xija to use the `numpydoc` style / extension.  The actual docstring migration was done fully automatically with the statement below after doing a --user local install of `pyment` with pip.
```
~/.local/bin/pyment --output numpydoc --write --convert xija
```
There is room for improvement in the actual values of parameters etc., but this PR is just about migration.
- [N/A] Passes unit tests on MacOS, linux, Windows (at least one required)
Built HTML documentation with no warnings. The API docs appear as expected.
=> Migrate all doc strings to use numpydoc

xija/model.py, xija/tests/test_models.py
Fixes #98 and removes some Py2 compatibility, and some whitespace changes tossed in by VS code.
- [N/A] Functional testing
Fixes #98
=> Allow model_spec to be provided as Path

docs/api.rst, xija/get_model_spec.py, xija/tests/test_get_model_spec.py
This adds functions that allow reliably getting xija model spec files from `$SKA/data/chandra_models`. 
By "reliable", the intent is that this will be used in production load review code, replacing the current practice of embedding the spec files into load review code.
The key benefit is allowing more agile xija model updates without requiring code updates and a full Ska3 release. The concept of allowing xija model updates without a code release has been put into practice for MATLAB tools, so extending this to SOT tools seems natural.
Along with this we need the following:
- Clone of the latest flight-approved models git repository in `$SKA/data/chandra_models`
- Process to keep this repo up to date. This can be a manual process that is documented in the Xija model update procedure on the …
=> Add module to allow getting model spec files from Ska data

xija/get_model_spec.py
The exception that occurs for a timeout on linux is apparently different from that on Mac. 
- [N/A] Functional testing
Fixes: dashboard test failure for xija
=> Add timeout error catch that occurs on linux

xija/get_model_spec.py
Fixes `get_model_spec` module to work on Windows.
- [N/A] Functional testing
Fixes #101
=> Fix get_model_spec to work on Windows

xija/component/heat.py
This update adds the ability to apply a heat power shift when a state msid matches a specified value.
In fitting a new fuel tank model, I found that there is a dependency on the SSR-B state, which can’t be accounted for in Xija without a new heat component. Since I anticipate using this type of state-based heat input for other models in other locations, I built a new flexible Xija heat component that can be defined to use a user-selected msid and state pair.
Here is an example that covers the key information one needs to use this update in the JSON model definition:
In the “comps” section:
```
{
"class_name": "MsidStatePower",
"init_args": [],
"init_kwargs": {
"P": 0.5,
"node": "pf0tank2t",
"state_msid": "COSSRBX",
"state_val": "ON "
},
"name": "cossrbx_on"
}
```
In the “pars” section: …
=> Add MSIDStatePower component

xija/get_model_spec.py
Instead of fetching all the releases on chandra_models release page, use github's idea of the 'latest' one.
I've already forgotten if we're run into issues with this that could be a problem for chandra_models, but at least it doesn't include pre-releases (which aren't a great conceptual fit with the checks in xija.get_model_spec).
We could probably also filter the old list or some such, but for the given use case, this made sense to me, and maybe it is helpful.
TA: I tried this in my repo after reverting my $SKA/data/chandra_models to 3.32 and it passed tests.
=> Use github's 'latest' release link for latest version

examples/delay/4hfspat_delay.json, examples/delay/4hfspat_delay.py, xija/component/base.py, xija/model.py
Add a new model component class `Delay` to delay the compute model values from ``node`` by ``delay`` ksec.
For a positive delay, the computed model value (`node.mval`) will be constant at the initial value for the first `delay` ksec. Conversely for a negative delay the values at the end will  be constant for `delay` ksec.
Made a new thermal model for 4HFSPAT using the `Delay` component (now included in the `examples/delay` directory).
- Confirmed that the model component introduces the expected positive or negative delay, with the endpoints being fixed as expected. 
- Confirmed that the `delay` parameter can be successfully fit with `xija_gui_fit` and that the result is reasonable (i.e. the model and data peaks visually line up).
=> Add a Delay model component

xija/gui_fit/app.py, xija/gui_fit/plots.py, xija/model.py
This PR resolves an issue where `xija_gui_fit` would seemingly randomly crash on Linux when manipulating plots. The exact reason is unknown, because I could never seem to produce a traceback of any kind, but many of the plot objects (such as `Figure` and `Axes` were being re-created every time the data itself needed an update due to a new model fit, etc. This PR implements the changing of the data on the plot itself (for several plot types) instead of re-creating the plot objects with every update, which appears to fix the problem. 
This PR also does the following:
* Uses `CxoTime` instead of `Chandra.Time`
* `annotate_limits` has been moved from being a method of the `XijaModel` class to being a function in the `xija_gui_fit` app, since this is the only place it's used
* Removes old …
=> Fix random crashes using xija_gui_fit on Linux, change limit names for annotation, use CxoTime

xija/gui_fit/plots.py
This fixes a bug in `xija_gui_fit` that was missed in the last PR. The bug surfaces when one toggles the limit lines on and off, and causes a crash.
=> This fixes a bug that was missed in the recent gui_fit PR

xija/get_model_spec.py
This PR makes ~~two changes~~ one minor change to `xija.get_model_spec`. ~~one minor and another that is API-breaking~~ 
1. Let the default for `repo_path` be `None` and then set it to `REPO_PATH` internally, so that calling routines from other packages can pass a `None` as default and they won't need to know about `REPO_PATH`.
~~2. In a couple of cases, I have found that it would be nice to know the path to the JSON file returned by `get_model_spec`, so it can be reported in logging or print statements. The way I currently do this is rather clunky--I import `REPO_PATH` from the same module. But this duplicates what's already being done in the function and is error-prone if something changes. So this change simply returns the path as the third argument--unfortunately this also breaks …
=> Set the default repo_path inside the get_model_spec function

xija/get_model_spec.py
The helper code to get the available model names in case of a bad input name was missing the `repo_path`.
```
(ska3) ➜  xija git:(get-model-spec-error-reporting) ✗ ipython
Python 3.8.3 (default, Jul  2 2020, 11:26:31) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from xija.get_model_spec import get_xija_model_spec                                                                                  
```
```
In [2]: spec, version = get_xija_model_spec('bep_pcb', version='bep_fep')                                                                    
```
```
In [3]: spec, version = get_xija_model_spec('bep_pab', version='bep_fep') …
```
=> Use the right repo path to get available model names

xija/gui_fit/plots.py, xija/limits.py
Based on the new limit scheme implemented in https://github.com/sot/chandra_models/pull/75, this PR implements two new functions in xija, `get_limit_spec` and `get_limit_color`. 
`get_limit_spec` takes a limit of the form `<system>.<type>.<direction>.<qualifier>` and returns a dict with these names as the keys:
```python
from xija.limits import get_limit_spec
limit_spec = get_limit_spec("planning.data_quality.high.acisi")
print(limit_spec)
```
which gives
```pycon
{
'system': 'planning', 
'type': 'data_quality', 
'direction': 'high', 
'qualifier': 'acisi'
}
```
This may have other uses eventually, but it was useful for `get_limit_color`, which uses it to assign colors for the various limits.
`get_limit_color` is used by `xija_gui_fit` to assign limit line colors, but I'll be using and …
=> Two new functions to handle limit strings, minor viz fixes for xija_gui_fit

xija/component/heat.py, xija/model.py
This PR makes tiny changes to remove uses of a few deprecated dtypes (https://github.com/sot/skare3/issues/753)
Fixes #
=> remove use of deprecated np.float and np.int

xija/component/heat.py
NOTE: The PR is finished but there is no expected hurry to merge it since I anticipate it will generate some discussion. 
This PR allows the heating on the ACIS FP from the earthshine into the ACIS radiator to depend on the Earth phase. The existing code assumes that the relevant earthshine is in the infrared, which should to zeroth order be the same regardless if the Earth is illuminated or not by the Sun. This code is an experimental feature to test the hypothesis that the model for the effect of earthshine on the temperature could be improved if we accounted for the Earth phase. 
This PR adds this capability by using the solar ephemeris along with the spacecraft ephemeris to compute the fraction of the  Earth which is illuminated by the Sun. It is currently an optional calculation …
=> Adjust earthshine effect based on Earth phase

xija/gui_fit/app.py, xija/gui_fit/plots.py
`xija_gui_fit` occasionally exhibits random crashes, especially when one is attempting to make new plots or pan/zoom within existing plots. This appears to be due to race conditions where an instruction to change a plot is made to a plot object that no longer exists. 
Along with https://github.com/sot/Ska.Matplotlib/pull/25, this PR seeks to avoid these crashes by doing the following:
* Avoid creating and re-creating `Figure` objects as much as possible, instead save the `Figure` object and update its data
* Add a short delay before updating plots after adding limit lines
* Caching rad zone times so they don't need to be created the first time you plot them
* General cleanup and simplification of code
This PR also adds the ability to manually specify the error limits in histogram plots, …
=> Fix instabilities in xija_gui_fit, add ability to adjust error limits in histogram plots

xija/model.py, xija/tests/test_models.py
This fixes a performance issue note on Slack in #thermal_working_group:
*I am doing some work that requires me to run the thermal models many, many times in a row, and was profiling my code when I noticed that the pm2thv1t model is running significantly slower than the pm1thv2t model, e.g. in my MATLAB setup:*
- pm1thv2t takes ~032ms to run, whereas
- pm2thv1t takes ~643ms to run
This PR vectorizes the bad times processing and minimizes the number of date --> time (CXC second) conversions. It also factors this processing out into a separate function (working to improve separation in this code).
Some points of note:
- The new code assumes that the `bad_times` in a JSON model spec file are in standard Year-day-of-year date format. There was another part of the code already making this …
=> Improve performance of bad_times and mask_times

xija/component/base.py, xija/gui_fit/plots.py
For models which execute very quickly, it is sometimes the case that during fitting a race condition of sorts is encountered when a plot that is being updated and a reference to the canvas object associated with the plot is lost (see Issue #126).
Unfortunately, the cause for this is still unknown. I was able to fix this problem by 1) Removing unnecessary references to the `canvas` object I was keeping around and also calling `canvas.flush_events` after every update.
This PR also adds some logic that affects the `resid__data` and histogram/dashboard plots in `xija_gui_fit` by masking out data that is under a "bad time" or a "mask time". The residuals are set to zero in such cases, but because of that they still appear in the plot and can give default plot limits that are unhelpful. We copy …
=> Avoid crashes in plotting, do not plot residuals of mask or bad times

xija/get_model_spec.py, xija/tests/test_get_model_spec.py
This refactors the `get_model_spec` module to use `ska_helpers.chandra_models`.
None, this is expected to be API compatible with the previous version.
Independent check of unit tests by Jean
No functional testing.
=> Refactor get_model_spec to use ska_helpers.chandra_models

models/acisfp/calc_model.py, xija/model.py
Use `cheta` instead of `Ska.engarchive`. This fixes the test warning noted in https://github.com/sot/cheta/pull/252.
Also use `ska_matplotlib` instead of `Ska.Matplotlib`.
Independent check of unit tests by [REVIEWER NAME]
Successfully ran `models/acisfp/calc_model.py` to check imports.
=> Use cheta not Ska.engarchive

xija/limits.py
This PR only changes the ACIS-I limit line for the FP temperature model to dark orange. This will make the plots in an upcoming version of `acis_thermal_check` easier to read. 
None
Not needed
Independent check of unit tests by [REVIEWER NAME]
No functional testing.
=> Change the ACIS-I limit line color to dark orange

xija/component/heat/solar.py
Convert an instance of `np.float` to `float`.
See: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. These deprecations are errors as of numpy 1.26. The code here is not covered in unit testing unfortunately.
```
(ska3-flight-2024.1rc4) ➜  xija git:(fix-np-float) pytest xija                 
================================================================ test session starts ================================================================
platform darwin -- Python 3.11.8, pytest-7.4.4, pluggy-1.4.0
rootdir: /Users/aldcroft/git
configfile: pytest.ini
plugins: timeout-2.2.0, anyio-4.3.0
collected 43 items                                                                                                                                  
xija/tests/test_get_model_spec.py ....... …
```
=> Change np.float to float

.pre-commit-config.yaml, xija/get_model_spec.py, xija/gui_fit/app.py, xija/model.py, xija/tests/test_get_model_spec.py
This makes it easier to run xija_gui_fit for model spec files taken from the Ska data `chandra_models` repo:
- Can specify a `--model-version` to pick a particular version.
- Previously names like `acisfp_spec_matlab` were not allowed because it automatically appended `_spec` to the model name. Now it tries both the original model name and one with `_spec` appended. Doing that appending was a mistake, but it is left there for back-compatibility.
In addition this fixes a bug when writing out the Python script that will generate a spec file.
```
(ska3-flight-2025.0rc2) ➜  xija git:(improved-model-spec-file) git rev-parse --short HEAD                            
2a67036
(ska3-flight-2025.0rc2) ➜  xija git:(improved-model-spec-file) pytest xija …
```
=> Minor interface improvements and fix bug writing Python spec file

docs/conf.py
Docs only fix to deal with 
```
ERROR: Invalid value `None` in intersphinx_mapping['http://docs.python.org/']. Expected a two-element tuple or list.
```
With this change "make html" worked for me.
=> Fix intersphinx_mapping syntax

xija/component/base.py, xija/tests/test_models.py
This improves on the fix from #142 using `cached_property` to define the `pars_dict` and `pars` properties with defaults as `{}` and `[]` respectively.
It also fixes poor coding style for a couple of properties.
This is not needed for Ska3 2025.1, it can go in a later release.
```
(ska3-flight-2025.0rc2) ➜  xija git:(recursion-redux) git rev-parse --short HEAD
39633c7
(ska3-flight-2025.0rc2) ➜  xija git:(recursion-redux) pytest xija
===================================================== test session starts ======================================================
platform darwin -- Python 3.12.8, pytest-8.3.4, pluggy-1.5.0
rootdir: /Volumes/git
configfile: pytest.ini
plugins: doctestplus-1.3.0, anyio-4.7.0, timeout-2.3.1
collected 44 items …
```
=> Improved implementation for pars_dict and pars attributes + pickle test
